using System.Diagnostics;
using AoC2025.Day01;
using AoC2025.Day02;
using AoC2025.Day03;
using AoC2025.Day04;
using AoC2025.Day05;
using AoC2025.Day06;
using AoC2025.Day07;
using AoC2025.Day08;
using AoC2025.Day09;
using AoC2025.Day10;
using AoC2025.Day11;
using AoC2025.Day12;

Console.WriteLine("Welcome to AoC 2025!");
Console.WriteLine("Day01");
Console.WriteLine("====");
Console.Write("Part1:");
new Day01().Part1();
Console.Write("Part2:");
new Day01().Part2();
Console.WriteLine();
Console.WriteLine("Day02");
Console.WriteLine("====");
Console.Write("Part1:");
new Day02().Part1();
Console.Write("Part2:");
new Day02().Part2();
Console.WriteLine();
Console.WriteLine("Day03");
Console.WriteLine("====");
Console.Write("Part1:");
new Day03().Part1And2(2);
Console.Write("Part2:");
new Day03().Part1And2(12);
Console.WriteLine();
Console.WriteLine("Day04");
Console.WriteLine("====");
Console.Write("Part1:");
new Day04().Part1();
Console.Write("Part2:");
new Day04().Part2();
Console.WriteLine();
Console.WriteLine("Day05");
Console.WriteLine("====");
Console.Write("Part1:");
new Day05().Part1();
Console.Write("Part2:");
new Day05().Part2();
Console.WriteLine();
Console.WriteLine("Day06");
Console.WriteLine("====");
Console.Write("Part1:");
new Day06().Part1();
Console.Write("Part2:");
new Day06().Part2();
Console.WriteLine();
Console.WriteLine("Day07");
Console.WriteLine("====");
Console.Write("Part1:");
new Day07().Part1();
Console.Write("Part2:");
new Day07().Part2();
Console.WriteLine();
Console.WriteLine("Day08");
Console.WriteLine("====");
Console.Write("Part1:");
new Day08().Part1And2(1000);
Console.Write("Part2:");
new Day08().Part1And2(int.MaxValue);
Console.WriteLine();
Console.WriteLine("Day09");
Console.WriteLine("====");
Console.Write("Part1:");
new Day09().Part1();
Console.Write("Part2:");
new Day09().Part2();
Console.WriteLine();
Console.WriteLine("Day10");
Console.WriteLine("====");
Console.Write("Part1:");
new Day10().Part1();
Console.Write("Part2:");
new Day10().Part2();
Console.WriteLine();
Console.WriteLine("Day11");
Console.WriteLine("====");
Console.Write("Part1:");
new Day11().Part1();
Console.Write("Part2:");
new Day11().Part2();
Console.WriteLine();
Console.WriteLine("Day12");
Console.WriteLine("====");
Console.Write("Part1:");
new Day12().Part1();
Console.Write("Part2:");
new Day12().Part2();
Console.WriteLine("The end.");
